### ISSUE TITLE
Flurry#logEvent(...) calls immediately after Flurry#init() fail

### ISSUE THREAD

**Issue by OnlyInAmerica** [flurry/android-AnalyticsSample#1]
There's a clear race condition in the Flurry Android SDK that causes events posted nearly after `Flurry.init(...)` to fail (`kFlurryEventFailed`). 

A typical use-case demonstrating this condition is trying to log an "Activity Launch" event in your main Activity's `onCreate()`, after calling `Flurry.init(...)` in your Application's `onCreate()`.

`Flurry.init()` should queue log events until after initialization is complete or, at the *very* least, block until initialization is truly complete.

**Comment by Ugonna** [comment]
You cannot log events in your main Activity's `onCreate()` with the SDK. The Flurry session would not be started at that point.  The session [only starts](https://developer.yahoo.com/flurry/docs/analytics/gettingstarted/android/#add-calls-to-init-onstartsession-and-onendsession) _after_ `Activity#onStart()` is called.

To log "Activity launch" events, you should call it after your Activity's `super.onStart()` (be sure to place conditions to prevent multiple log calls).

**Comment by OnlyInAmerica** [comment]
Oh, thanks for the quick response! This would be awesome to add to the Android Docs.

**Comment by pawanpandey-kiwi** [comment]
Same issue occuring at my end im using FlurryAnalytics-5.0.0. Its first event always fail. If I try logging same event with some delay using handler its posted sucessfully. I started session on activity onStart() and stopped is on activity.onStop().

**Comment by rollinsio** [comment]
@pawanpandey-kiwi We've updated the documentation that any events which need to be captured directly after initializing Flurry should be done in the Listener.  This is the simplest and easiest way to go about it.  That alternative is to block the main thread, which is not an option.
